import Navbar from './components/Navbar'
import './globals.css'

export const metadata = {
  title: 'WikiHunt',
  description: 'Generated by myself',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className='bg-gradient-to-r from-slate-400 to-slate-200'>
        <div className='bg-main_bg bg-contain bg-top bg-no-repeat'>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  )
}
